extern const GeoLayout isikle_cap_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout isikle_cap_geo[];
extern Lights1 isikle_cap_Brim__EMBLEM__lights;
extern Lights1 isikle_cap_Hat__CAP__lights;
extern Lights1 isikle_cap_Brim_Dark__EMBLEM__lights;
extern u8 isikle_cap_cherry_rgba16[];
extern Vtx isikle_cap_Cap_DL_mesh_layer_1_vtx_0[46];
extern Gfx isikle_cap_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx isikle_cap_Cap_DL_mesh_layer_1_vtx_1[69];
extern Gfx isikle_cap_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx isikle_cap_Cap_DL_mesh_layer_1_vtx_2[8];
extern Gfx isikle_cap_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx isikle_cap_Cherry_mesh_layer_4_vtx_0[4];
extern Gfx isikle_cap_Cherry_mesh_layer_4_tri_0[];
extern Gfx mat_isikle_cap_Brim__EMBLEM_[];
extern Gfx mat_isikle_cap_Hat__CAP_[];
extern Gfx mat_isikle_cap_Brim_Dark__EMBLEM_[];
extern Gfx mat_isikle_cap_Cherry[];
extern Gfx mat_revert_isikle_cap_Cherry[];
extern Gfx isikle_cap_Cap_DL_mesh_layer_1[];
extern Gfx isikle_cap_Cherry_mesh_layer_4[];
extern Gfx isikle_cap_material_revert_render_settings[];
